### ISSUE TITLE
Need to check digest header values on POSTed data and reject if not a match

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-kms-http#10]

**Comment by mattcollier** [comment]
@dlongley is this still needed?  If so, I think some additional detail is needed if we are to assign this to anyone.

**Comment by dlongley** [comment]
Yes, this is still needed (very much so). Currently, we do not check to make sure that the HTTP body submitted hashes to the same value in the `digest` header. Without this, we're not confirming that the body digest that was signed in fact matches the body that was submitted and is then operated on. We need a middleware/something that will compute a digest on the body that can be passed into a verification function as an `expectedDigest` for comparison.

**Comment by dmitrizagidulin** [comment]
Once https://github.com/digitalbazaar/http-digest-header/issues/5 is implemented, use it here.

**Comment by mandyvenables** [comment]
@JSAssassin has said this is completed.
