### ISSUE TITLE
The error thrown by _verifyHost should include the host it expects and the host it received in the message.

### ISSUE THREAD

**Issue by gannan08** [digitalbazaar/bedrock-kms-http#12]
https://github.com/digitalbazaar/bedrock-kms-http/blob/use-keystores/lib/http.js#L617

**Comment by mattcollier** [comment]
Link to code on master: https://github.com/digitalbazaar/bedrock-kms-http/blob/master/lib/http.js#L419-L428

This is a matter of adding the `allowedHost` value and `url` to the error details.
