### ISSUE TITLE
Query for all keystores controlled by controller

### ISSUE THREAD

**Issue by mandyvenables** [digitalbazaar/bedrock-kms-http#31]
Inside of `get keystore configs by query` endpoint.

This was a [TODO](https://github.com/digitalbazaar/bedrock-kms-http/commit/7a48af64d483d47d3b0fda47f819260fafdf39df#diff-1c0f1c434b17b7f8795d44a51a14320aR121).

**Comment by dlongley** [comment]
Closing as getting keystores by query has been removed. It may be reintroduced in the future with a redesign that works with the new authz.
