### ISSUE TITLE
Investigate error logging issues in http handler.

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-kms-http#35]
An error that is thrown in the following HTTP handler gets surfaces in no way on the server.  The specific error I encountered was an attempt to require a non-existent module in connection with: https://github.com/digitalbazaar/bedrock-kms/issues/35

My expectation was that any error thrown inside an `asyncHandler` would be passed up to the default error handler in `bedrock-express` and be put into the bedrock error log.  This is not happening at least in this particular case.

https://github.com/digitalbazaar/bedrock-kms-http/blob/master/lib/http.js#L241-L243

**Comment by dlongley** [comment]
This may have improved somewhat with a fix in `webkms-switch@9.1` to call `onError`. Needs investigation.

**Comment by dlongley** [comment]
This has been resolved by calling the `onError` handler when running a KMS operation.
