### ISSUE TITLE
Consolidate documentLoader with 'bedrock-kms'

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalbazaar/bedrock-kms-http#52]
Currently, `bedrock-kms-http` and `bedrock-kms` are using two separate `documentLoader` instances. 
Need to refactor it so that there's only one (created in `-kms-http`, passed down into `-kms`).

See also https://github.com/digitalbazaar/bedrock-kms-http/issues/44

**Comment by dlongley** [comment]
This will be addressed by #54.
