### ISSUE TITLE
Refactor against bedrock-kms

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-kms-http#9]
There are some abstractions being broken between this module and bedrock-kms that have arisen over time as redesigns have occurred. This should be explored, possibly merging most of the code in this module (or all of it) into `bedrock-kms`. This module should perhaps be reserved for handling proxying to the kms server only and `bedrock-kms` would handle everything else. Perhaps this module should be renamed on that basis.

**Comment by mattcollier** [comment]
Is this comment still applicable?

**Comment by dlongley** [comment]
> Is this comment still applicable?

Yes. We still haven't handled cleaning up the proxy/don't proxy design. I think the general concept in the OP makes sense -- moving the main HTTP API to bedrock-kms and then making this module just handle proxying (for when a KMS should be externally accessible).

**Comment by mattcollier** [comment]
@dlongley first, is your latest thinking still reflected here?

Second, there was an effort made at creating a generic HTTP proxy mechanism here, is that not a valid solution?

https://github.com/digitalbazaar/bedrock-http-proxy/pull/1

I don't think the solution should involve moving HTTP stuffs into `bedrock-kms`, if the functionality must be specific, maybe `bedrock-kms-http-proxy`?

One way or the other this probably needs to get implemented soon right?

**Comment by dlongley** [comment]
> first, is your latest thinking still reflected here?

Haven't thought about it in a while. Doesn't really matter though -- we just need someone to look into this and do the right thing (TM).

> Second, there was an effort made at creating a generic HTTP proxy mechanism here, is that not a valid solution?

I don't know if we can get away with using a generic proxy here (probably not, but I can't say -- someone will have to get into the details of what we need to figure it out).

> I don't think the solution should involve moving HTTP stuffs into bedrock-kms, if the functionality must be specific, maybe bedrock-kms-http-proxy?

I suspect that would be fine.

> One way or the other this probably needs to get implemented soon right?

Yes, absolutely.

**Comment by dlongley** [comment]
The proxy design was replaced by `ipAllowList`. Closing.
